FROM debian:bookworm AS builder
RUN apt update && apt --no-install-recommends install -y libssl-dev\
    openssh-client \
    pkg-config \
    software-properties-common\
    python3-pip\
    python3-jinja2\
    libboost-dev \
    libgnutls28-dev openssl libtiff-dev pybind11-dev\
    qtbase5-dev libqt5core5a libqt5widgets5\
    meson python3-yaml python3-ply\
    libglib2.0-dev libgstreamer-plugins-base1.0-dev\
    ninja-build\
    python3-dev\
    libdrm-dev \
    libjpeg-dev\
    libsdl2-dev\
    libtiff-dev \
    libevent-dev \
    g++\
    liblttng-ust1
     
COPY artifacts/*.deb  packages/
RUN dpkg -i ./packages/*.deb
COPY test-lib/* /test-lib/
WORKDIR test-lib
RUN meson build && cd build && ninja && ./libcamera-test
